#!/bin/bash
# Copyright (C) 2019 Omar Castro <omar.castro.360@gmail.com>

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.


ROFI_ARGS=()
if ! [[ -z "${rofi_theme_left_click:-$rofi_theme}" ]]; then
  ROFI_ARGS+=( -theme "${rofi_theme_left_click:-$rofi_theme}" )
fi
if ! [[ -z "$rofi_window_anchor" ]]; then
  ROFI_ARGS+=( -m -3 -theme-str '#window {anchor:'"$rofi_window_anchor"'; width:50ch;}' )
fi

TMP_DIR="$(mktemp -d)"
export COMMAND_FILE="$TMP_DIR/command"
echo "OPEN-ROFI" > $COMMAND_FILE

while : 
do
  COMMAND="$(cat $COMMAND_FILE)"
  echo "" > $COMMAND_FILE
  case "$COMMAND" in
    OPEN-ROFI )
      rofi "${ROFI_ARGS[@]}" -markup-rows -eh 2 -lines 5 -modi blocks -show blocks -blocks-wrap "$( dirname "${BASH_SOURCE[0]}" )/rofi-block";;
    CONNECT\ *)
      notify-send "$COMMAND";;
    *)
      exit
  esac
done
